malwaredomainlist:
  url : http://www.malwaredomainlist.com/hostslist/hosts.txt
  format : ip domain

StevenBlack:
  url : https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts"
  format : ip domain

ad_simple:
  url : https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
  format: domain

justdomain:
  url : https://mirror1.malwaredomains.com/files/justdomains
  format : domain

cameleon:
  url : http://sysctl.org/cameleon/hosts
  format : ip domain

simple_tracking:
  url : https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
  format : domain

pihole-blacklist:
  url : https://raw.githubusercontent.com/mhhakim/pihole-blocklist/master/list.txt
  format : domain

the-big-list-of-hacked-malware-web-site:
  url : https://raw.githubusercontent.com/mitchellkrogza/The-Big-List-of-Hacked-Malware-Web-Sites/master/hacked-domains.list
  format : domain

malware-domain-list:
  url : https://raw.githubusercontent.com/Ultimate-Hosts-Blacklist/MalwareDomainList.com/master/domains.list
  format : domain

sophos:
  url : https://raw.githubusercontent.com/austinheap/sophos-xg-block-lists/master/malware-domain-list.txt
  format : domain

openpish:
  url : https://openphish.com/feed.txt
  format : url

blackbook:
  url : https://raw.githubusercontent.com/stamparm/blackbook/master/blackbook.txt
  format : domain

phishing.database:
  url : https://raw.githubusercontent.com/mitchellkrogza/Phishing.Database/master/phishing-domains-ACTIVE.txt
  format : domain

blockconvert:
  url : https://raw.githubusercontent.com/mkb2091/blockconvert/master/output/domains.txt
  format : domain

dbl.oisd.nl:
  url : https://dbl.oisd.nl/
  format : domain

dblmobile.oisd.nl:
  url : https://dblmobile.oisd.nl/
  format : domain

zerodot1.coiner:
  url : https://zerodot1.gitlab.io/CoinBlockerLists/list.txt
  format : domain

zerodot1.coiner.list:
  url : https://zerodot1.gitlab.io/CoinBlockerLists/list.txt
  format : domain

zerodot1.coiner.list.browser:
  url : https://zerodot1.gitlab.io/CoinBlockerLists/list_browser.txt 
  format : domain

zerodot1.coiner.list.optional:
  url : https://zerodot1.gitlab.io/CoinBlockerLists/list_optional.txt 
  format : domain

crazymax:
  url : https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt
  format : ip domain

BBcan:
  url : https://gist.githubusercontent.com/BBcan177/4a8bf37c131be4803cb2/raw/343ff780e15205b4dd0de37c86af34cfb26b2fbe/MS-2
  format : domain

crazymax:
  url : https://adaway.org/hosts.txt
  format : ip domain

firebog:
  url : https://v.firebog.net/hosts/AdguardDNS.txt
  format : domain

anudeep:
  url : https://raw.githubusercontent.com/anudeepND/blacklist/master/adservers.txt
  format : ip domain

bigdargon:
  url : https://raw.githubusercontent.com/bigdargon/hostsVN/master/hosts
  format : ip domain

#!!! star